footprint: [
  [0.35, -0.35],
  [-0.35, -0.35],
  [-0.35, 0.2],
  [-0.788, 0.636],
  [-0.636, 0.778],
  [-0.2, 0.35],
  [0.35, 0.35]
]

inflation_layer:
  enabled: true
  cost_scaling_factor: 3.0
  inflation_radius: 0.5