footprint: [
  [0.35, -0.35],
  [-0.35, -0.35],
  [-0.35, 0.2],
  [-0.788, 0.636],
  [-0.636, 0.778],
  [-0.2, 0.35],
  [0.35, 0.35]
]

map_type: costmap
cost_scaling_factor: 0.2
inflation_radius: 1.2