local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: true
  static_layer:
    enabled: true
    map_topic: "map"
  rolling_window: false
  resolution: 0.05
  transform_tolerance: 0.5
  plugins:
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
