TebLocalPlannerROS:
    max_vel_x: 0.5
    max_vel_x_backwards: 0.2
    max_vel_theta: 0.5
    acc_lim_x: 0.8
    acc_lim_theta: 1.0
    min_turning_radius: 0.0

    min_obstacle_dist: 0.3
    inflation_dist: 0.6
    
    dt_ref: 0.3
    dt_hysteresis: 0.1
    global_plan_overwrite_orientation: true
    max_global_plan_lookahead_dist: 3.0
    feasibility_check_no_poses: 5
    
    xy_goal_tolerance: 0.15
    yaw_goal_tolerance: 0.1
    free_goal_vel: false