DWAPlannerROS:
    max_vel_x: 0.5
    min_vel_x: 0.0
    max_vel_theta: 0.5
    min_vel_theta: -0.5
    
    acc_lim_x: 0.8
    acc_lim_theta: 1.0
    
    yaw_goal_tolerance: 0.1
    xy_goal_tolerance: 0.1
    latch_xy_goal_tolerance: false
    
    sim_time: 2.0
    vx_samples: 10
    vy_samples: 0  
    vth_samples: 20
    
    path_distance_bias: 32.0
    goal_distance_bias: 24.0
    occdist_scale: 0.02 
    forward_point_distance: 1.0