footprint: [
  [0.35, -0.35],
  [-0.35, -0.35],
  [-0.35, -0.1],
  [-1.0, -0.1],
  [-1.0, 0.1],
  [-0.35, 0.1],
  [-0.35, 0.35],
  [0.35, 0.35]
]

map_type: costmap
cost_scaling_factor: 0.2
inflation_radius: 1.2
